# -*- coding: utf-8 -*-
"""streamlit.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uc9pZ54bqie8rT-XCQwfpRnm6HMT6cup
"""
import pandas as pd
import streamlit as st
import pickle

st.title('our first streamlit app')
st.write('you can choose according parameters')

with open('model.p','rb') as f1:
    loaded_model = pickle.load(f1)
F1 = st.slider('External Risk Estimate：',1,500,5,1)
F2 = st.slider('Months Since Oldest Trade Open：',1,1000,5,1)
F4 = st.slider('Average Months in File：',1,500,5,1)
F5 = st.slider('Number Satisfactory Trades：',1,500,5,1)
F12 = st.slider('Number of Total Trades：',1,500,5,1)
F14 = st.slider('Percent Installment Trades：',1,500,5,1)
F18 = st.slider('Net Fraction Revolving Burden：',1,500,5,1)
F23 = st.slider('Percent Trades with Balance：',1,500,5,1)


data = {'F1': [F1], 'F2': [F2], 'F4': [F4], 'F5': [F5],
        'F12': [F12], 'F14': [F14], 'F18': [F18], 'F23': [F23]}
new_data = pd.DataFrame(data)

result = loaded_model.predict(new_data)

result_text = 'good,you can accept this applicant' if result == 1 else 'bad,you cannot accept this applicant'

st.text('The prediction for this applicant is %s'%(result_text))
